(part "IM03GR"
    (packageRef "IM06GR")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
        (port "6" (symbPinId 6) (portName "6") (portType INOUT))
        (port "7" (symbPinId 7) (portName "7") (portType INOUT))
        (port "8" (symbPinId 8) (portName "8") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "161")
    (property "Mouser_Part_Number" "655-IM03GR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/TE-Connectivity/IM03GR?qs=h8jywBNgiq20bLq7q22y%252Bg%3D%3D")
    (property "Manufacturer_Name" "TE Connectivity")
    (property "Manufacturer_Part_Number" "IM03GR")
    (property "Description" "DPDT telecom SMT relay, 2A 5Vdc coil")
    (property "Datasheet_Link" "https://datasheet.datasheetarchive.com/originals/distributors/Datasheets_SAMA/af0478e68580ade93768a4593bd7be66.pdf")
    (property "symbolName1" "IM03GR")
)
