(part "PE4312C-Z"
    (packageRef "QFN50P400X400X90-21N-D")
    (interface
        (port "1" (symbPinId 1) (portName "C16") (portType INOUT))
        (port "2" (symbPinId 2) (portName "RF1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "DATA") (portType INOUT))
        (port "4" (symbPinId 4) (portName "CLOCK") (portType INOUT))
        (port "5" (symbPinId 5) (portName "LE") (portType INOUT))
        (port "6" (symbPinId 6) (portName "VDD_1") (portType INOUT))
        (port "7" (symbPinId 7) (portName "PUP1") (portType INOUT))
        (port "8" (symbPinId 8) (portName "PUP2") (portType INOUT))
        (port "9" (symbPinId 9) (portName "VDD_2") (portType INOUT))
        (port "10" (symbPinId 10) (portName "GND_1") (portType INOUT))
        (port "11" (symbPinId 11) (portName "GND_2") (portType INOUT))
        (port "12" (symbPinId 12) (portName "VSS_EXT/GND") (portType INOUT))
        (port "13" (symbPinId 13) (portName "P/S") (portType INOUT))
        (port "14" (symbPinId 14) (portName "RF2") (portType INOUT))
        (port "15" (symbPinId 15) (portName "C8") (portType INOUT))
        (port "16" (symbPinId 16) (portName "C4") (portType INOUT))
        (port "17" (symbPinId 17) (portName "C2") (portType INOUT))
        (port "18" (symbPinId 18) (portName "GND_3") (portType INOUT))
        (port "19" (symbPinId 19) (portName "C1") (portType INOUT))
        (port "20" (symbPinId 20) (portName "C0.5") (portType INOUT))
        (port "21" (symbPinId 21) (portName "EP") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "81-PE4312C-Z")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/pSemi/PE4312C-Z?qs=l7cgNqFNU1hgFbGgRtu7ww%3D%3D")
    (property "Manufacturer_Name" "Peregrine Semiconductor")
    (property "Manufacturer_Part_Number" "PE4312C-Z")
    (property "Description" "RF ATTENUATOR 31.5DB 50OHM 20QFN")
    (property "Datasheet_Link" "https://www.psemi.com/pdf/datasheets/pe4312ds.pdf")
    (property "symbolName1" "PE4312C-Z")
)
