(part "SI5351A-B-GTR"
    (packageRef "SOP50P490X110-10N")
    (interface
        (port "1" (symbPinId 1) (portName "VDD") (portType INOUT))
        (port "2" (symbPinId 2) (portName "XA") (portType INOUT))
        (port "3" (symbPinId 3) (portName "XB") (portType INOUT))
        (port "4" (symbPinId 4) (portName "SCL") (portType INOUT))
        (port "5" (symbPinId 5) (portName "SDA") (portType INOUT))
        (port "6" (symbPinId 6) (portName "CLK2") (portType INOUT))
        (port "7" (symbPinId 7) (portName "VDDO") (portType INOUT))
        (port "8" (symbPinId 8) (portName "GND") (portType INOUT))
        (port "9" (symbPinId 9) (portName "CLK1") (portType INOUT))
        (port "10" (symbPinId 10) (portName "CLK0") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "634-SI5351A-B-GTR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Skyworks-Solutions-Inc/SI5351A-B-GTR?qs=p9T7GgSe1IEYql%252BRMAlVcw%3D%3D")
    (property "Manufacturer_Name" "Skyworks")
    (property "Manufacturer_Part_Number" "SI5351A-B-GTR")
    (property "Description" "Clock Generator 10MHz to 100MHz-IN 160MHz-OUT 10-Pin MSOP T/R")
    (property "Datasheet_Link" "https://www.mouser.de/datasheet/2/472/Si5351_B-2507774.pdf")
    (property "symbolName1" "SI5351A-B-GTR")
)
