(part "LMH6612MAX_NOPB"
    (packageRef "SOIC127P600X175-8N")
    (interface
        (port "1" (symbPinId 1) (portName "OUT_A") (portType INOUT))
        (port "2" (symbPinId 2) (portName "-IN_A") (portType INOUT))
        (port "3" (symbPinId 3) (portName "+IN_A") (portType INOUT))
        (port "4" (symbPinId 4) (portName "V-") (portType INOUT))
        (port "5" (symbPinId 5) (portName "+IN_B") (portType INOUT))
        (port "6" (symbPinId 6) (portName "-IN_B") (portType INOUT))
        (port "7" (symbPinId 7) (portName "OUT_B") (portType INOUT))
        (port "8" (symbPinId 8) (portName "V+") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "926-LMH6612MAX/NOPB")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/LMH6612MAX-NOPB?qs=7lkVKPoqpbYkkjxJnAARvQ%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "LMH6612MAX/NOPB")
    (property "Description" "Single Supply, Dual 345 MHz Rail-to-Rail Output Amplifier")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/LMH6612")
    (property "symbolName1" "LMH6612MAX_NOPB")
)
