(part "ESD9B3_3ST5G"
    (packageRef "SODFL1006X40N")
    (interface
        (port "1" (symbPinId 1) (portName "K") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "122")
    (property "Mouser_Part_Number" "863-ESD9B3.3ST5G")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/onsemi/ESD9B3.3ST5G?qs=yU2N9dt%252BrfmXrPf3vhgUEA%3D%3D")
    (property "Manufacturer_Name" "onsemi")
    (property "Manufacturer_Part_Number" "ESD9B3.3ST5G")
    (property "Description" "SZ Prefix for Automotive and Other Applications Requiring Unique Site and Control Change Requirements ; AECQ101 Qualified and PPAP Capable ; This is a PbFree Device; Low Capacitance 15 pF; Low Clamping Voltage; Small Body Outline Dimensions: 0.039 x 0.024 (1.0mm x 0.60mm); Low Body Height: 0.016 (0.4 mm); Response Time is < 1 ns; IEC6100042 Level 4 ESD Protection; Low Leakage")
    (property "Datasheet_Link" "https://www.onsemi.com/pub/Collateral/ESD9B-D.PDF")
    (property "symbolName1" "ESD9B3_3ST5G")
)
