(part "LT8471IFE_PBF"
    (packageRef "SOP65P640X120-21N")
    (interface
        (port "1" (symbPinId 1) (portName "C1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "E1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "VIN1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "PG1") (portType INOUT))
        (port "5" (symbPinId 5) (portName "FB1") (portType INOUT))
        (port "6" (symbPinId 6) (portName "OV/UV") (portType INOUT))
        (port "7" (symbPinId 7) (portName "RT") (portType INOUT))
        (port "8" (symbPinId 8) (portName "SS1") (portType INOUT))
        (port "9" (symbPinId 9) (portName "SYNC") (portType INOUT))
        (port "10" (symbPinId 10) (portName "GND_1") (portType INOUT))
        (port "11" (symbPinId 11) (portName "GND_2") (portType INOUT))
        (port "12" (symbPinId 12) (portName "GND_3") (portType INOUT))
        (port "13" (symbPinId 13) (portName "C3") (portType INOUT))
        (port "14" (symbPinId 14) (portName "SHOUT") (portType INOUT))
        (port "15" (symbPinId 15) (portName "SS2") (portType INOUT))
        (port "16" (symbPinId 16) (portName "FB2") (portType INOUT))
        (port "17" (symbPinId 17) (portName "PG2") (portType INOUT))
        (port "18" (symbPinId 18) (portName "VIN2") (portType INOUT))
        (port "19" (symbPinId 19) (portName "E2") (portType INOUT))
        (port "20" (symbPinId 20) (portName "C2") (portType INOUT))
        (port "21" (symbPinId 21) (portName "GND_4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "584-LT8471IFE#PBF")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Analog-Devices/LT8471IFEPBF?qs=hVkxg5c3xu%2FiDctk9AXMtQ%3D%3D")
    (property "Manufacturer_Name" "Analog Devices")
    (property "Manufacturer_Part_Number" "LT8471IFE#PBF")
    (property "Description" "DC/DC CONVERTER, MULTITOPOLOGY, 50V, TSSOP-20; Supply Voltage:50V; No. of Step-Down DC - DC Converters:2; No. of LDO Regulators:-; No. of Regulated Outputs:2; Digital IC Case:TSSOP; No. of Pins:20Pins; Operating Temperature Min:-40CRoHS Compliant: Yes")
    (property "Datasheet_Link" "https://www.analog.com/media/en/technical-documentation/data-sheets/8471fd.pdf")
    (property "symbolName1" "LT8471IFE_PBF")
)
