(part "MBASU31LSB7225KTNA01"
    (packageRef "MBASx31x")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "32")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Manufacturer_Name" "TAIYO YUDEN")
    (property "Manufacturer_Part_Number" "MBASU31LSB7225KTNA01")
    (property "Description" "MULTILAYER CERAMIC CAPACITORS[Multilayer Ceramic Capacitors (High dielectric type) for Telecommunications Infrastructure and Industrial Equipment]")
    (property "Datasheet_Link" "https://ds.yuden.co.jp/TYCOMPAS/or/detail?pn=MBASU31LSB7225KTNA01")
    (property "symbolName1" "MBASU31LSB7225KTNA01")
)
