(part "DAC8562SDGSR"
    (packageRef "SOP50P490X110-10N")
    (interface
        (port "1" (symbPinId 1) (portName "VOUTA") (portType INOUT))
        (port "2" (symbPinId 2) (portName "VOUTB") (portType INOUT))
        (port "3" (symbPinId 3) (portName "GND") (portType INOUT))
        (port "4" (symbPinId 4) (portName "%LDAC%") (portType INOUT))
        (port "5" (symbPinId 5) (portName "%CLR%") (portType INOUT))
        (port "6" (symbPinId 6) (portName "%SYNC%") (portType INOUT))
        (port "7" (symbPinId 7) (portName "SCLK") (portType INOUT))
        (port "8" (symbPinId 8) (portName "DIN") (portType INOUT))
        (port "9" (symbPinId 9) (portName "AVDD") (portType INOUT))
        (port "10" (symbPinId 10) (portName "VREFIN/VREFOUT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-DAC8562SDGSR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/DAC8562SDGSR?qs=L4ss%2FyqpMWQjhHzbOFnTNg%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "DAC8562SDGSR")
    (property "Description" "16-bit, dual-channel, low-power, ultra-low glitch, voltage output DAC with 2.5V, 4ppm/C reference")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/dac8562")
    (property "symbolName1" "DAC8562SDGSR")
)
