(part "P6SMBJ5_0CA"
    (packageRef "DIONM5437X240N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "637-P6SMBJ5.0CA")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Diotec-Semiconductor/P6SMBJ5.0CA?qs=OlC7AqGiEDl52k1IDrEg7g%3D%3D")
    (property "Manufacturer_Name" "Diotec")
    (property "Manufacturer_Part_Number" "P6SMBJ5.0CA")
    (property "Description" "ESD Suppressors / TVS Diodes TVS, SMB,  150C,  600W, Bidir")
    (property "Datasheet_Link" "https://www.mouser.de/datasheet/2/849/p6smbj65-2578601.pdf")
    (property "symbolName1" "P6SMBJ5_0CA")
)
