(part "5413879-2"
    (packageRef "54138792")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "MH1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "MH2") (portType INOUT))
        (port "G1" (symbPinId 4) (portName "GND") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "571-5413879-2")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/TE-Connectivity/5413879-2?qs=dJbzCyn%252BCFbDLsMjA0NFtQ%3D%3D")
    (property "Manufacturer_Name" "TE Connectivity")
    (property "Manufacturer_Part_Number" "5413879-2")
    (property "Description" "BNC RF Interface, Jack, 50 ohm, Bayonet, 4 GHz Operating Frequency, Cable-to-Board, 1 Position, Printed Circuit Board, Board Mount / Panel Mount")
    (property "Datasheet_Link" "https://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=5413879&DocType=Customer%20Drawing&DocLang=English&PartCntxt=5413879-2&DocFormat=pdf")
    (property "symbolName1" "5413879-2")
)
