(part "ESDS312DBVR"
    (packageRef "SOT95P280X145-5N")
    (interface
        (port "1" (symbPinId 1) (portName "NC_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "NC_2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "I/O1") (portType INOUT))
        (port "5" (symbPinId 5) (portName "I/O2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "595-ESDS312DBVR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/ESDS312DBVR?qs=byeeYqUIh0PGNqB7QuJpTA%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "ESDS312DBVR")
    (property "Description" "3.6V Data-Line Surge and 30kV ESD Protection Diode Array")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/esds312")
    (property "symbolName1" "ESDS312DBVR")
)
