(part "BLM21PG600SN1D"
    (packageRef "BLM21AG102BH1J")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "155")
    (property "Mouser_Part_Number" "81-BLM21P600S")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Murata-Electronics/BLM21PG600SN1D?qs=LbqjZSvnDswFXSg06XQ50A%3D%3D")
    (property "Manufacturer_Name" "Murata Electronics")
    (property "Manufacturer_Part_Number" "BLM21PG600SN1D")
    (property "Description" "Murata Ferrite Bead (Chip Ferrite Bead), 2 x 1.25 x 0.85mm (805), 60 impedance at 100 MHz")
    (property "Datasheet_Link" "https://www.murata.com/en-us/products/productdetail?partno=BLM21PG600SN1%23")
    (property "symbolName1" "BLM21PG600SN1D")
)
