(part "SI-60118-F"
    (packageRef "SI60118F")
    (interface
        (port "1" (symbPinId 1) (portName "TD+") (portType INOUT))
        (port "2" (symbPinId 2) (portName "TCT") (portType INOUT))
        (port "3" (symbPinId 3) (portName "TD-") (portType INOUT))
        (port "4" (symbPinId 4) (portName "RD+") (portType INOUT))
        (port "5" (symbPinId 5) (portName "RCT") (portType INOUT))
        (port "6" (symbPinId 6) (portName "RD-") (portType INOUT))
        (port "7" (symbPinId 7) (portName "NC_1") (portType INOUT))
        (port "8" (symbPinId 8) (portName "NC_2") (portType INOUT))
        (port "9" (symbPinId 9) (portName "A_GREEN_1") (portType INOUT))
        (port "10" (symbPinId 10) (portName "K_GREEN_1") (portType INOUT))
        (port "11" (symbPinId 11) (portName "A_GREEN_2") (portType INOUT))
        (port "12" (symbPinId 12) (portName "K_GREEN_2") (portType INOUT))
        (port "MH1" (symbPinId 13) (portName "MH1") (portType INOUT))
        (port "MH2" (symbPinId 14) (portName "MH2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "530-SI-60118-F")
    (property "Mouser_Price/Stock" "https://www.mouser.com/Search/ProductDetail.aspx?qs=SRYZG9HaIQ1pVFtjOaj56g%3d%3d")
    (property "Manufacturer_Name" "BelFuse")
    (property "Manufacturer_Part_Number" "SI-60118-F")
    (property "Description" "MagJack 10/100BASE-T | 1X1 | G/G | -40 to 85C | Tab Down | RoHS ")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/1/SI-60118-F.pdf")
    (property "symbolName1" "SI-60118-F")
)
