(part "THS4271D"
    (packageRef "SOIC127P600X175-8N")
    (interface
        (port "1" (symbPinId 1) (portName "NC_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "IN−") (portType INOUT))
        (port "3" (symbPinId 3) (portName "IN+") (portType INOUT))
        (port "4" (symbPinId 4) (portName "VS−") (portType INOUT))
        (port "5" (symbPinId 5) (portName "NC_2") (portType INOUT))
        (port "6" (symbPinId 6) (portName "VOUT") (portType INOUT))
        (port "7" (symbPinId 7) (portName "VS+") (portType INOUT))
        (port "8" (symbPinId 8) (portName "NC_3") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-THS4271D")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/THS4271D?qs=ZmJdcv7QZ9ppdaigv2fizw%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "THS4271D")
    (property "Description" "Super-Fast Ultra-Low Distortion High Speed Amplifier")
    (property "Datasheet_Link" "http://www.ti.com/lit/ds/symlink/ths4271.pdf")
    (property "symbolName1" "THS4271D")
)
