(part "ASE-25_000MHZ-LC-T"
    (packageRef "ASE24576MHZLCT")
    (interface
        (port "1" (symbPinId 1) (portName "TRI-STATE_(STBY)") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND/CASE") (portType INOUT))
        (port "3" (symbPinId 3) (portName "OUTPUT") (portType INOUT))
        (port "4" (symbPinId 4) (portName "VDD") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "171")
    (property "Mouser_Part_Number" "815-ASE25.000MHZLCT")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/ABRACON/ASE-25.000MHZ-LC-T?qs=ShQ8XZQtgRuW6p4KtHOZPQ%3D%3D")
    (property "Manufacturer_Name" "ABRACON")
    (property "Manufacturer_Part_Number" "ASE-25.000MHZ-LC-T")
    (property "Description" "ASE-25.000MHZ-LC-T Crystal Oscillator, 25 MHz, +/-50ppm CMOS 15pF, 4-Pin SMD, 3.2 x 2.5 x 1.2mm")
    (property "Datasheet_Link" "https://abracon.com/Oscillators/ASEseries.pdf")
    (property "symbolName1" "ASE-25_000MHZ-LC-T")
)
